INSERT INTO ITEMS VALUES ('A', 50);
INSERT INTO ITEMS VALUES ('B', 30);
INSERT INTO ITEMS VALUES ('C', 20);
INSERT INTO ITEMS VALUES ('D', 15);

INSERT INTO ACTIVEPROMOTION VALUES ('A', 'A', 3, 130, '');
INSERT INTO ACTIVEPROMOTION VALUES ('B', 'B', 2, 45, '');
INSERT INTO ACTIVEPROMOTION VALUES ('C', 'CD', 1, 0, 'C,D');
INSERT INTO ACTIVEPROMOTION VALUES ('D', 'CD',1, 30,'C,D');
